import type { Metadata } from 'next';
import './globals.css';
import QueryProviderConfig from '@/utils/provider/query/QueryProviderConfig';

export const metadata: Metadata = {
  title: 'jm4293',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="ko">
      <body>
        <QueryProviderConfig>{children}</QueryProviderConfig>
      </body>
    </html>
  );
}
